name: tasker_0001
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  table_calendar: ^3.0.9
  flutter_slidable: ^3.0.1
  uuid: ^4.3.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true